modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/Wehavecookies56/Kingdom-Keys/issues" #optional
[[mods]] #mandatory
modId="kingdomkeys" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Kingdom Keys" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/kingdom-keys-re-coded" #optional
credits="Remorse Code, Collecter, EthanGold, Sr.Gato and Lewis Weekes for supporting the mod on Patreon! Square Enix for Kingdom Hearts" #optional
authors="Wehavecookies56, Abelatox, Wynd, stel1034" #optional
description='''
A mod inspired by Kingdom Hearts adding various elements from the games.
'''
[[dependencies.kingdomkeys]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31.2.10,)" #mandatory
    ordering="BEFORE"
    side="BOTH"